name: maec-project
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=23.1.2
  - conda-forge::cudatoolkit==11.8.0
  - pip:
    - tensorflow==2.12.*
    - nvidia-cudnn-cu11==8.6.0.163
    - note-seq==0.0.5
    - visual_midi==1.1.0
